services:
  db:
    image: postgres:15
    container_name: postgres_container
    networks:
      - app_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mirea_books
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432" # Экспонирует порт для доступа снаружи (необязательно в продакшене)

  app:
    build: .
    container_name: market_app
    volumes:
      - ./:/app
    environment:
      MARKET_SERVER_PORT: "8080"
      MARKET_DB_USER: "postgres"
      MARKET_DB_PASSWORD: "postgres"
      MARKET_DB_NAME: "mirea_books"
      MARKET_DB_HOST: db
      MARKET_DB_PORT: "5432"
    networks:
      - app_network
    depends_on:
      - db
    ports:
      - "8080:8080" # Прокси-порт приложения

networks:
  app_network:
    driver: bridge